#
###################################
# Site wide configuration
####################################
#
title: zanywhale
email: zanywhale@kaist.ac.kr
description: A simple and awesome blog theme powered by jekyll.
url: https://zanywhale.github.io # the base hostname & protocol for your site
keywords: ["Security", "CTF", "Python"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: DongHyeon Oh
  avatar: zanywhale-logo.png
  job: "Computer Security Researcher"
  bio: "zanywhale"
  email: zanywhale@kaist.ac.kr
  disqus-shortname: zanywhale
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zanywhale #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: donghyeon-oh #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
